Upgrade to WinSW 2.1.2, as 1.17 isn't working on my Windows Server 2012 machine
On 1.17 I'm seeing:
Error: Unable to access jarfile C:\ec2-sshd\ec2-sshd.exe\ec2-sshd.jar